const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{SfondoTransizione: 0},
	{Titolo: 0},
	{BottonePlay: 0},
	{BottoneFullScreen: 0},
	{BottoneAudio: 0},
	{canMove: 0},
	{Platform: 0},
	{Sine: 0},
	{Player: 0},
	{Jumpthru: 0},
	{Piattaforma: 0},
	{Touch: 0},
	{Keyboard: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Solid: 0},
	{Muro: 0},
	{PunteggioaSchermo: 0},
	{PunteggioTotalizzato: 0},
	{PunteggioGameOver: 0},
	{Audio: 0},
	{Browser: 0},
	{Nemico: 0},
	{nuvola: 0},
	{LocalStorage: 0},
	{start: 0},
	{maxY: 0},
	{ProssimoTerreno: 0},
	{sonoMorto: 0},
	{metri: 0},
	{punteggio: 0},
	{migliorPunteggio: 0},
	{posX: 0},
	{posY: 0},
	{numeroCasuale: 0}
];

self.InstanceType = {
	SfondoTransizione: class extends self.ISpriteInstance {},
	Titolo: class extends self.ISpriteInstance {},
	BottonePlay: class extends self.ISpriteInstance {},
	BottoneFullScreen: class extends self.ISpriteInstance {},
	BottoneAudio: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Piattaforma: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	Muro: class extends self.ISpriteInstance {},
	PunteggioaSchermo: class extends self.ISpriteFontInstance {},
	PunteggioTotalizzato: class extends self.ISpriteInstance {},
	PunteggioGameOver: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Nemico: class extends self.ISpriteInstance {},
	nuvola: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {}
}